# Generated by Django 5.1.3 on 2024-11-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='signature',
            field=models.CharField(default='Your name or Favourite Quote', max_length=140),
        ),
    ]
